CHANGE MASTER TO MASTER_HOST='mysql-master', MASTER_USER='repl', MASTER_PASSWORD='password' FOR CHANNEL "master";
CHANGE MASTER TO MASTER_HOST='mysql-slave', MAS-TER_USER='replslave', MASTER_PASSWORD='password' FOR CHANNEL "slave";
START SLAVE FOR CHANNEL "master";
START SLAVE FOR CHANNEL "slave";
